DATA_DIR: "C:/Users/siran/.cache/kagglehub/datasets/adityajn105/flickr8k/versions/1"

PATHS:
  IMAGES: "Images"
  CAPTIONS: "captions.csv"
  WORD_DICT: "word_dict.csv"



SEPARATOR_KEYS:
  START: "<start>"
  PAD: "<pad>"
  END: "<end>"